
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import os


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/daniil/report/myvenv/build/assets/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("440x956")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 956,
    width = 440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    222.0,
    478.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    222.0,
    909.0,
    image=image_image_2
)

canvas.create_rectangle(
    220.0,
    866.0,
    327.0,
    925.0,
    fill="#FFFFFF",
    outline="")

def switch_to_page2():
    window.destroy()
    os.system("python3 /home/daniil/Human_project/second_page.py")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=switch_to_page2, #кнопка для перехода в чаты
    relief="flat",
    bg="#FFFFFF"
)
button_1.place(
    x=238.0,
    y=863.0,
    width=78.0,
    height=50.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    222.0,
    27.0,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
